function change1(){
    document.getElementById('pic').src='whitetshirt.jpeg';
}
function change2(){
    document.getElementById('pic').src='blacktshirt.jpeg';
}
function change3(){
    document.getElementById('pic').src='bluetshirt.jpeg';
}
function change4(){
    document.getElementById('pic').src='redtshirt.jpeg';
}
function change5(){
    document.getElementById('pic').src='greentshirt.jpeg';
}